### ISSUE TITLE
Autosuggest box moves down when header is fixed where search box is present.

### ISSUE THREAD

**Issue by AnshuHanda** [unbxd/autosuggest#24] opened 2015-06-09 12:53 UTC
In int.localbanya.com , header is fixed. When user scroll down and search something in search box then autosuggest position gets weird . It moves down on the page

**Comment by rahulcs** [comment] 2015-06-15 17:07
@AnshuHanda is this fixed? can you share a screenshot? explain it to @santosh1994

**Comment by santosh1994** [comment] 2015-06-16 06:23
.unbxd-as-wrapper.unbxd-as-extra-right {

   1. z-index: 999999 !important;
   2. position: fixed !important;
   3. /* top: 34px !important; */

}


change the position to absolute or remove position property

**Comment by rahulcs** [comment] 2015-06-16 06:27
cool.. @AnshuHanda if the issue is fixed with this, close it.

**Closed** 2015-06-16 07:29 UTC
